package MetaData

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ElectNewWorkerTeam) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "WorkerPubList":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "WorkerPubList")
				return
			}
			if z.WorkerPubList == nil {
				z.WorkerPubList = make(map[string]uint64, zb0002)
			} else if len(z.WorkerPubList) > 0 {
				for key := range z.WorkerPubList {
					delete(z.WorkerPubList, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 uint64
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "WorkerPubList")
					return
				}
				za0002, err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "WorkerPubList", za0001)
					return
				}
				z.WorkerPubList[za0001] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ElectNewWorkerTeam) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "WorkerPubList"
	err = en.Append(0x81, 0xad, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.WorkerPubList)))
	if err != nil {
		err = msgp.WrapError(err, "WorkerPubList")
		return
	}
	for za0001, za0002 := range z.WorkerPubList {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "WorkerPubList")
			return
		}
		err = en.WriteUint64(za0002)
		if err != nil {
			err = msgp.WrapError(err, "WorkerPubList", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ElectNewWorkerTeam) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "WorkerPubList"
	o = append(o, 0x81, 0xad, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74)
	o = msgp.AppendMapHeader(o, uint32(len(z.WorkerPubList)))
	for za0001, za0002 := range z.WorkerPubList {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendUint64(o, za0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ElectNewWorkerTeam) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "WorkerPubList":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WorkerPubList")
				return
			}
			if z.WorkerPubList == nil {
				z.WorkerPubList = make(map[string]uint64, zb0002)
			} else if len(z.WorkerPubList) > 0 {
				for key := range z.WorkerPubList {
					delete(z.WorkerPubList, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 uint64
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WorkerPubList")
					return
				}
				za0002, bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WorkerPubList", za0001)
					return
				}
				z.WorkerPubList[za0001] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ElectNewWorkerTeam) Msgsize() (s int) {
	s = 1 + 14 + msgp.MapHeaderSize
	if z.WorkerPubList != nil {
		for za0001, za0002 := range z.WorkerPubList {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.Uint64Size
		}
	}
	return
}
